@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/MooseX-Declare-Context-WithOptions-Patch-Extensible/project>
	deps:runtime-requirement         [ deps:on "MooseX::Declare 0.39"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

